# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs = -Dfile.encoding=UTF-8 -Xmx4G
org.gradle.daemon = true
# Enable parallel task execution, this makes a multi-project a bit faster.
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.warning.mode = none
# Disable the default dependency on the Kotlin Standard Library.
kotlin.stdlib.default.dependency = false
kotlin.code.style = official

# Minecraft Environment Properties
java.version = 25
minecraft.version = 26.2

## Mod Properties ##

# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod.group = com.kinhiro
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod.namespace = hostility_staff
# The human-readable display name for the mod.
mod.name = Hostility Staff
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod.license = MIT
# The mod version. See https://semver.org/
mod.version = 1.0.1
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod.authors = Kinhiro Zane
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod.description = A highly mysterious mob brawl mod.
# The issue tracker of the mod.
mod.issue = https://github.com/kinhirozane/hostility_staff/issues
# The homepage of the mod.
mod.homepage = https://modrinth.com/mod/hostility_staff
# The credits of the mod.
mod.credits = contributors
